export const COLORS = {
  light: {
    primary: "#FF7A00",
    secondary: "#5c5c5cff",
    danger: "#FF3B3B",
    success: "#4CAF50",
    background: "#f5f5f5",
    text: "#000",
    card: "#fff",
    input: "#ddd",
    inputText: "#111",
    button: "#000",
    buttonText: "#fff",
  },
  dark: {
    primary: "#FF7A00",
    secondary: "#a1a1a1ff",
    danger: "#FF3B3B",
    success: "#4CAF50",
    background: "#111",
    text: "#fff",
    card: "#222",
    input: "#303030ff",
    inputText: "#fff",
    button: "#fff",
    buttonText: "#000",
  },
};
